### ISSUE TITLE
Two flip divs on the page

### ISSUE THREAD

**Issue by abraxascorner** [roncioso/Flip-jQuery#10]
Hi,

there is no possibility to have two flip animations on one page.

**Comment by roncioso** [comment]
I cannot reproduce you issue, can you please provide an example?

**Comment by Chaser324** [comment]
I've successfully used in multiple places on a single page as well.

**Comment by abraxascorner** [comment]
Sorry for my late response, I was on vacation. It seems that there was a problem combining this script with some other plugin. I managed eventually to solve the problem.

Once again, sorry for late response.

Best regards,
Nemanja
